**NUMPY**

In [2]:
#Numpy Library
import numpy as np

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
import yfinance as yf

In [7]:
symbol = 'AMD'
start = '2014-01-01'
end = '2024-12-31'

dataset = yf.download(symbol, start, end)
dataset.head()

[*********************100%***********************]  1 of 1 completed


Price      Close  High   Low  Open    Volume
Ticker       AMD   AMD   AMD   AMD       AMD
Date                                        
2014-01-02  3.95  3.98  3.84  3.85  20548400
2014-01-03  4.00  4.00  3.88  3.98  22887200
2014-01-06  4.13  4.18  3.99  4.01  42398300
2014-01-07  4.18  4.25  4.11  4.19  42932100
2014-01-08  4.18  4.26  4.14  4.23  30678700

In [8]:
open_array = np.array(dataset['Open'])
open_array

array([[  3.8499999 ],
       [  3.98000002],
       [  4.01000023],
       ...,
       [125.51999664],
       [124.37000275],
       [123.55999756]], shape=(2767, 1))

In [9]:
print("First element:", open_array[0])
print("Second element:", open_array[1])
print("Second element:", open_array[-1])


First element: [3.8499999]
Second element: [3.98000002]
Second element: [123.55999756]


In [10]:
print(open_array[2:5])
print(open_array[:5])
print(open_array[5:])
print(open_array[:])

[[4.01000023]
 [4.19000006]
 [4.23000002]]
[[3.8499999 ]
 [3.98000002]
 [4.01000023]
 [4.19000006]
 [4.23000002]]
[[  4.19999981]
 [  4.09000015]
 [  4.19000006]
 ...
 [125.51999664]
 [124.37000275]
 [123.55999756]]
[[  3.8499999 ]
 [  3.98000002]
 [  4.01000023]
 ...
 [125.51999664]
 [124.37000275]
 [123.55999756]]


In [11]:
volume = np.array(dataset['Volume'])


In [12]:
volume[0] = 0    
print(volume) 

[[       0]
 [22887200]
 [42398300]
 ...
 [24998200]
 [32924000]
 [30501600]]


In [16]:
volume[2:5] = np.array([4, 6, 8]).reshape(-1, 1)
print(volume)

[[       0]
 [22887200]
 [       4]
 ...
 [24998200]
 [32924000]
 [30501600]]


In [18]:
add_numbers = np.array([1,2,3]).reshape(-1, 1)
np.concatenate((volume, add_numbers), axis=0)

array([[       0],
       [22887200],
       [       4],
       ...,
       [       1],
       [       2],
       [       3]], shape=(2770, 1))