**PYTHON MATRIX**

In [36]:
import numpy as np

In [37]:
import warnings 
warnings.filterwarnings("ignore")


In [38]:
import yfinance as yf


In [39]:
symbol = 'NVDA'
start = '2015-01-01'
end = '2024-01-01'


In [40]:
dataset = yf.download(symbol,start,end)
dataset.head()

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open     Volume
Ticker          NVDA      NVDA      NVDA      NVDA       NVDA
Date                                                         
2015-01-02  0.483099  0.486699  0.475419  0.483099  113680000
2015-01-05  0.474940  0.484539  0.472780  0.483099  197952000
2015-01-06  0.460540  0.476139  0.460060  0.475659  197764000
2015-01-07  0.459340  0.467980  0.457900  0.463900  321808000
2015-01-08  0.476619  0.479499  0.464380  0.464620  283780000

In [41]:
df = dataset.drop(['High','Low','Volume'], axis = 1)
df.head()

Price          Close      Open
Ticker          NVDA      NVDA
Date                          
2015-01-02  0.483099  0.483099
2015-01-05  0.474940  0.483099
2015-01-06  0.460540  0.475659
2015-01-07  0.459340  0.463900
2015-01-08  0.476619  0.464620

In [42]:
a = np.array(df)
a

array([[ 0.48309913,  0.48309913],
       [ 0.47493953,  0.48309918],
       [ 0.46054   ,  0.47565933],
       ...,
       [49.39844513, 49.4924116 ],
       [49.50341034, 49.62436712],
       [49.50341034, 49.79430147]], shape=(2264, 2))

In [43]:
print("a = ", a)
print("a[1] = ", a[1])
print("a[1][1] = ", a[1][1])
print("a[0][-1] = ", a[0][-1])

a =  [[ 0.48309913  0.48309913]
 [ 0.47493953  0.48309918]
 [ 0.46054     0.47565933]
 ...
 [49.39844513 49.4924116 ]
 [49.50341034 49.62436712]
 [49.50341034 49.79430147]]
a[1] =  [0.47493953 0.48309918]
a[1][1] =  0.483099182858812
a[0][-1] =  0.4830991327762604


In [44]:
column = [];
for row in a:
    column.append(row[1])

print("Second column = ", column)

Second column =  [np.float64(0.4830991327762604), np.float64(0.483099182858812), np.float64(0.4756593309911262), np.float64(0.4638999121553492), np.float64(0.4646199225414205), np.float64(0.47829922645819956), np.float64(0.4797391651235464), np.float64(0.4761393943273643), np.float64(0.4667797945442587), np.float64(0.4770992986134475), np.float64(0.4696596517971261), np.float64(0.48237913530654236), np.float64(0.477819405349319), np.float64(0.4881388170473568), np.float64(0.49605839376653793), np.float64(0.49485859274864197), np.float64(0.48717886697106627), np.float64(0.4768593917481294), np.float64(0.46365997336634474), np.float64(0.47133969602950626), np.float64(0.46365999426651494), np.float64(0.4742195952036105), np.float64(0.4811793496173327), np.float64(0.4842991135168292), np.float64(0.4912588230362929), np.float64(0.4866989827763353), np.float64(0.48957878772922553), np.float64(0.5039782260870945), np.float64(0.5279770736520264), np.float64(0.5339770125727294), np.float64(0.53

In [45]:
type(a)

numpy.ndarray

In [46]:
a = np.arange(4)
print('a = ', a)

b = np.arange(12).reshape(2,6)
print('b = ', b)

a =  [0 1 2 3]
b =  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [64]:
A = np.column_stack((dataset['High'], dataset['Low']))
B = np.column_stack((dataset['Open'], dataset['Close']))

print(A)
print(B)

[[ 0.486699    0.47541945]
 [ 0.48453913  0.47277963]
 [ 0.4761393   0.46006002]
 ...
 [49.66134687 49.06656905]
 [49.86527397 49.39345102]
 [49.97823433 48.73269984]]
[[ 0.48309913  0.48309913]
 [ 0.48309918  0.47493953]
 [ 0.47565933  0.46054   ]
 ...
 [49.4924116  49.39844513]
 [49.62436712 49.50341034]
 [49.79430147 49.50341034]]


In [65]:
c = A + B
print("Addition Matrix: \n", c)

Addition Matrix: 
 [[ 0.96979814  0.95851858]
 [ 0.96763831  0.94771916]
 [ 0.95179863  0.92060002]
 ...
 [99.15375847 98.46501418]
 [99.48964108 98.89686136]
 [99.7725358  98.23611018]]


In [66]:
d = A - B
print("Substraction Matrix: \n", d)

Substraction Matrix: 
 [[ 3.59986966e-03 -7.67968380e-03]
 [ 1.43994801e-03 -2.15989341e-03]
 [ 4.79972965e-04 -4.79972965e-04]
 ...
 [ 1.68935264e-01 -3.31876076e-01]
 [ 2.40906852e-01 -1.09959320e-01]
 [ 1.83932854e-01 -7.70710499e-01]]


In [68]:
e = A.dot(B.T)
print("Multiplication of two matrices: \n", e)

Multiplication of two matrices: 
 [[4.64798590e-01 4.60919378e-01 4.50452593e-01 ... 4.75728889e+01
  4.76870140e+01 4.77697209e+01]
 [4.62479864e-01 4.58622192e-01 4.48209489e-01 ... 4.73355888e+01
  4.74491518e+01 4.75314917e+01]
 [4.52277083e-01 4.48523198e-01 4.38356145e-01 ... 4.62915322e+01
  4.64026517e+01 4.64835642e+01]
 ...
 [4.76953706e+01 4.72950091e+01 4.62190006e+01 ... 4.88167204e+03
  4.89337541e+03 4.90181458e+03]
 [4.79518040e+01 4.75487753e+01 4.64665426e+01 ... 4.90791234e+03
  4.91967694e+03 4.92815076e+03]
 [4.76871667e+01 4.72895295e+01 4.62159709e+01 ... 4.88086294e+03
  4.89257309e+03 4.90106610e+03]]


In [71]:
print([A[:2, :4],B[:2, :4]])

[array([[0.486699  , 0.47541945],
       [0.48453913, 0.47277963]]), array([[0.48309913, 0.48309913],
       [0.48309918, 0.47493953]])]
