***ARRAY SELECTION NUMPY***

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style = 'white', color_codes = True)

import warnings
warnings.filterwarnings('ignore')


In [4]:
import yfinance as yf

In [7]:
symbol = 'AAPL'
start = '2014-01-01'
end = '2024-01-01'

dataset = yf.download(symbol, start, end)
dataset.columns = dataset.columns.get_level_values(0)
dataset.head()

[*********************100%***********************]  1 of 1 completed


Price           Close       High        Low       Open     Volume
Date                                                             
2014-01-02  17.192822  17.314045  17.158320  17.272083  234684800
2014-01-03  16.815161  17.210533  16.798064  17.184424  392467600
2014-01-06  16.906864  16.996071  16.585779  16.705448  412610800
2014-01-07  16.785954  16.969963  16.720058  16.918988  317209200
2014-01-08  16.892252  16.957525  16.743987  16.747716  258529600

In [10]:
# Create Data
dataset['Open_Close'] = (dataset['Open'] - dataset['Close'])/dataset['Open']
dataset['High_Low'] = (dataset['High'] - dataset['Low'])/dataset['Low']
dataset['Increase_Decrease'] = np.where(dataset['Volume'].shift(-1) > dataset['Volume'],1,0)
dataset['Buy_Sell_on_Open'] = np.where(dataset['Open'].shift(-1) > dataset['Open'],1,0)
dataset['Buy_Sell'] = np.where(dataset['Close'].shift(-1) > dataset['Close'],1,0)
dataset['Returns'] = dataset['Close'].pct_change()
dataset = dataset.dropna()
dataset.head()

Price           Close       High        Low       Open     Volume  Open_Close  \
Date                                                                            
2014-01-06  16.906864  16.996071  16.585779  16.705448  412610800   -0.012057   
2014-01-07  16.785954  16.969963  16.720058  16.918988  317209200    0.007863   
2014-01-08  16.892252  16.957525  16.743987  16.747716  258529600   -0.008630   
2014-01-09  16.676535  16.997931  16.640167  16.996065  279148800    0.018800   
2014-01-10  16.565260  16.809570  16.508378  16.779420  304976000    0.012763   

Price       High_Low  Increase_Decrease  Buy_Sell_on_Open  Buy_Sell   Returns  
Date                                                                           
2014-01-06  0.024738                  0                 1         0  0.005454  
2014-01-07  0.014946                  0                 0         1 -0.007152  
2014-01-08  0.012753                  1                 1         0  0.006333  
2014-01-09  0.021500                  1                 0         0 -0.012770  
2014-01-10  0.018245                  1                 0         1 -0.006673

***FEATURE SELECTION IN ARRAY***

In [11]:
feature_data = np.asarray(dataset)
feature_data

array([[ 1.69068642e+01,  1.69960709e+01,  1.65857786e+01, ...,
         1.00000000e+00,  0.00000000e+00,  5.45361512e-03],
       [ 1.67859535e+01,  1.69699629e+01,  1.67200581e+01, ...,
         0.00000000e+00,  1.00000000e+00, -7.15157130e-03],
       [ 1.68922520e+01,  1.69575248e+01,  1.67439874e+01, ...,
         1.00000000e+00,  0.00000000e+00,  6.33258316e-03],
       ...,
       [ 1.91745819e+02,  1.92093281e+02,  1.89700797e+02, ...,
         1.00000000e+00,  1.00000000e+00,  5.17844702e-04],
       [ 1.92172699e+02,  1.93244849e+02,  1.91765676e+02, ...,
         0.00000000e+00,  0.00000000e+00,  2.22628000e-03],
       [ 1.91130325e+02,  1.92986726e+02,  1.90336138e+02, ...,
         0.00000000e+00,  0.00000000e+00, -5.42415058e-03]],
      shape=(2514, 11))

In [12]:
type(feature_data)

numpy.ndarray

In [13]:
feature_data[0]

array([ 1.69068642e+01,  1.69960709e+01,  1.65857786e+01,  1.67054480e+01,
        4.12610800e+08, -1.20569133e-02,  2.47375976e-02,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  5.45361512e-03])

In [14]:
feature_data[0][1]

np.float64(16.996070923177157)

In [15]:
#row 1, all columns
feature_data[1, :]

array([ 1.67859535e+01,  1.69699629e+01,  1.67200581e+01,  1.69189876e+01,
        3.17209200e+08,  7.86300528e-03,  1.49464046e-02,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00, -7.15157130e-03])

In [18]:
#one column with one row in array
feature_data[:, 0]

array([ 16.90686417,  16.78595352,  16.89225197, ..., 191.74581909,
       192.17269897, 191.13032532], shape=(2514,))

In [19]:
np.hstack((feature_data, feature_data[:, [0]]))

array([[ 1.69068642e+01,  1.69960709e+01,  1.65857786e+01, ...,
         0.00000000e+00,  5.45361512e-03,  1.69068642e+01],
       [ 1.67859535e+01,  1.69699629e+01,  1.67200581e+01, ...,
         1.00000000e+00, -7.15157130e-03,  1.67859535e+01],
       [ 1.68922520e+01,  1.69575248e+01,  1.67439874e+01, ...,
         0.00000000e+00,  6.33258316e-03,  1.68922520e+01],
       ...,
       [ 1.91745819e+02,  1.92093281e+02,  1.89700797e+02, ...,
         1.00000000e+00,  5.17844702e-04,  1.91745819e+02],
       [ 1.92172699e+02,  1.93244849e+02,  1.91765676e+02, ...,
         0.00000000e+00,  2.22628000e-03,  1.92172699e+02],
       [ 1.91130325e+02,  1.92986726e+02,  1.90336138e+02, ...,
         0.00000000e+00, -5.42415058e-03,  1.91130325e+02]],
      shape=(2514, 12))

In [20]:
#use transpose of particular column
feature_data.T[0]

array([ 16.90686417,  16.78595352,  16.89225197, ..., 191.74581909,
       192.17269897, 191.13032532], shape=(2514,))

In [21]:
#get more than one column
feature_data[:, [0,2]]

array([[ 16.90686417,  16.58577861],
       [ 16.78595352,  16.72005815],
       [ 16.89225197,  16.74398742],
       ...,
       [191.74581909, 189.70079744],
       [192.17269897, 191.76567599],
       [191.13032532, 190.33613821]], shape=(2514, 2))

In [23]:
#remove element
r = feature_data[:, -1]
r = np.delete(r, 0)
r

array([-0.00715157,  0.00633258, -0.01277019, ...,  0.00051784,
        0.00222628, -0.00542415], shape=(2513,))

In [24]:
print("Compare 2 array data")
print("Original Data:")
print(feature_data)
print("-" * 50)
a=np.delete(feature_data, 0, axis=0) # Delete the first column
print("New array data:\n", a)

Compare 2 array data
Original Data:
[[ 1.69068642e+01  1.69960709e+01  1.65857786e+01 ...  1.00000000e+00
   0.00000000e+00  5.45361512e-03]
 [ 1.67859535e+01  1.69699629e+01  1.67200581e+01 ...  0.00000000e+00
   1.00000000e+00 -7.15157130e-03]
 [ 1.68922520e+01  1.69575248e+01  1.67439874e+01 ...  1.00000000e+00
   0.00000000e+00  6.33258316e-03]
 ...
 [ 1.91745819e+02  1.92093281e+02  1.89700797e+02 ...  1.00000000e+00
   1.00000000e+00  5.17844702e-04]
 [ 1.92172699e+02  1.93244849e+02  1.91765676e+02 ...  0.00000000e+00
   0.00000000e+00  2.22628000e-03]
 [ 1.91130325e+02  1.92986726e+02  1.90336138e+02 ...  0.00000000e+00
   0.00000000e+00 -5.42415058e-03]]
--------------------------------------------------
New array data:
 [[ 1.67859535e+01  1.69699629e+01  1.67200581e+01 ...  0.00000000e+00
   1.00000000e+00 -7.15157130e-03]
 [ 1.68922520e+01  1.69575248e+01  1.67439874e+01 ...  1.00000000e+00
   0.00000000e+00  6.33258316e-03]
 [ 1.66765347e+01  1.69979305e+01  1.66401674e+01 

In [26]:
print('Example Stock with 11 features: ', '\n', feature_data[0], 'Stock Data Features')

Example Stock with 11 features:  
 [ 1.69068642e+01  1.69960709e+01  1.65857786e+01  1.67054480e+01
  4.12610800e+08 -1.20569133e-02  2.47375976e-02  0.00000000e+00
  1.00000000e+00  0.00000000e+00  5.45361512e-03] Stock Data Features


In [28]:
selected_features = feature_data[:, [1, 2, 3, 10]]

In [29]:
x_data_features = selected_features[1:, :]
x_data_features[x_data_features == ''] = 0.0
x_data = x_data_features

selected_features_labels = selected_features[0, 1:]
print('Selected Features Names: \n', selected_features_labels)
print('First few stocks with Features, no labels: ','\n', x_data[0:2, :], '...')
print(np.size(x_data[:, 0]), 'Stocks by', np.size(x_data[0, :]), 'Features')

Selected Features Names: 
 [1.65857786e+01 1.67054480e+01 5.45361512e-03]
First few stocks with Features, no labels:  
 [[ 1.69699629e+01  1.67200581e+01  1.69189876e+01 -7.15157130e-03]
 [ 1.69575248e+01  1.67439874e+01  1.67477158e+01  6.33258316e-03]] ...
2513 Stocks by 4 Features


In [32]:
#place dataset into input(x) and output(y) variables

x_strings = x_data_features[:, 1:] #takes off tickers, as they can't be tensor'd
raw_x = x_strings.astype(float)  #convert strings to float

#num_of_features = np.size(raw_x[0, :])
print('Features for Tensor: ', np.size(raw_x[0, :]))

Features for Tensor:  3
